# Dependabot basic setup for version control

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Maintain dependencies for javascript
  - package-ecosystem: "npm"
    directory: "/frontend"
    target-branch: "main"
    schedule:
      interval: "daily"
  # Maintain dependencies for javascript
  - package-ecosystem: "npm"
    directory: "/slidev"
    target-branch: "main"
    schedule:
      interval: "daily"
