name: Continuous integration
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
on:
  workflow_call:
  pull_request:
    paths:
      - '**.js'
      - '**.cs'
      - '**.json'
      - '**.ts'
      - '**.vue'
      - '**.css'
      - '**.yaml'
      - '**.yml'

jobs:

  build-frontend:
    name: Build frontend
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: |
             frontend/pnpm-lock.yaml
             slidev/pnpm-lock.yaml
      - name: Install modules
        run: pnpm --prefix ./frontend install && pnpm --prefix ./slidev install
      - name: Build
        run: pnpm --prefix ./frontend run build && pnpm --prefix ./slidev run build-explainers

  lint-frontend:
    name: Lint and format frontend
    runs-on: ubuntu-20.04
    needs: [ build-frontend ]
    strategy:
      fail-fast: false
      matrix:
        project: [ 'frontend', 'slidev' ]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: '${{ matrix.project }}/pnpm-lock.yaml'
      - name: Install modules
        run: pnpm --prefix ./${{ matrix.project }} install
      - name: Perform linter
        run: pnpm --prefix ./${{ matrix.project }} run lint
      - name: Perform code formatter
        run: pnpm --prefix ./${{ matrix.project }} run format
